#!/usr/bin/env python3
"""
Verify that the agent produced a correct clue_list.json in the workspace.

Scoring:
  - ops/ directory exists: 5 pts
  - clue_list.json exists: 5 pts
  - clue_list.json is valid JSON: 10 pts
  - It has a "clues" array with correct structure (id, type, clue): 10 pts
  - The set of ids matches exactly the expected 5 documents: 40 pts (8 pts each, 5 expected)
  - No extra ids: 10 pts (deduct 2 per extra id, min 0)
  - For each expected id, the clue string equals the first 80 characters of the corresponding summary: 20 pts (4 pts each)
Total = 100 pts
"""
import sys
import json
import os
import pathlib

def main():
    workspace = sys.argv[1] if len(sys.argv) > 1 else "."
    wdir = pathlib.Path(workspace)

    # Precomputed expected data (generated by env_builder)
    expected = {
        "RPT-2025-001": {
            "type": "report",
            "summary": "HelioSync Edge Inference Fabric enables real-time model deployment on factory floor gateways. This report reviews three production pilots."
        },
        "RPT-2025-004": {
            "type": "report",
            "summary": "HelioSync Edge Inference Fabric requires TPM 2.0 and kernel 5.10+. This guide covers setup and monitoring."
        },
        "PRES-2025-102": {
            "type": "presentation",
            "summary": "HelioSync Edge Inference Fabric integration patterns for industrial partners. Key API changes in v2.1."
        },
        "MED-2025-001": {
            "type": "media_sample",
            "summary": "The CEO discusses the strategic importance of the HelioSync Edge Inference Fabric for IoT deployments."
        },
        "MED-2025-003": {
            "type": "media_sample",
            "summary": "HelioSync Edge Inference Fabric enables sub-5ms inference at the edge. Demo with a robotic arm."
        }
    }

    details = []
    total_score = 0

    def add_detail(item, score, max_score, passed, reason):
        details.append({
            "item": item,
            "score": score,
            "max_score": max_score,
            "passed": passed,
            "reason": reason
        })
        return score

    # 1. ops/ directory exists
    ops_dir = wdir / "ops"
    if ops_dir.is_dir():
        total_score += add_detail("ops/ directory exists", 5, 5, True, "Found ops/ directory")
    else:
        total_score += add_detail("ops/ directory exists", 0, 5, False, "Missing ops/ directory")

    # 2. clue_list.json exists
    clue_path = ops_dir / "clue_list.json"
    if clue_path.is_file():
        total_score += add_detail("clue_list.json exists", 5, 5, True, "File found")
    else:
        total_score += add_detail("clue_list.json exists", 0, 5, False, "File missing")
        # If file doesn't exist, we can still try to score zero for remaining items
        # but we just return now with partial score
        _write_score(total_score, details, wdir)
        return

    # 3. Valid JSON
    try:
        with open(clue_path, "r") as f:
            data = json.load(f)
        total_score += add_detail("JSON is valid", 10, 10, True, "Parsed successfully")
    except (json.JSONDecodeError, Exception) as e:
        total_score += add_detail("JSON is valid", 0, 10, False, f"Invalid JSON: {str(e)}")
        _write_score(total_score, details, wdir)
        return

    # 4. Clues array with expected structure
    clues = data.get("clues", None)
    if not isinstance(clues, list):
        total_score += add_detail("clues array present", 0, 10, False, "Missing or non-list 'clues'")
        _write_score(total_score, details, wdir)
        return

    structure_ok = True
    for clue in clues:
        if not isinstance(clue, dict):
            structure_ok = False
            break
        if not all(k in clue for k in ("id", "type", "clue")):
            structure_ok = False
            break
    if structure_ok:
        total_score += add_detail("clue entries have correct fields (id, type, clue)", 10, 10, True, "All entries valid")
    else:
        total_score += add_detail("clue entries have correct fields", 0, 10, False, "Some entries missing required fields")
        _write_score(total_score, details, wdir)
        return

    # 5. Check id set matches expected (5 documents)
    found_ids = {c["id"] for c in clues}
    expected_ids = set(expected.keys())
    common_ids = found_ids & expected_ids
    missing_ids = expected_ids - found_ids
    extra_ids = found_ids - expected_ids

    id_score = 0
    max_id_score = 40
    if missing_ids:
        id_score = 0
        reason = f"Missing ids: {sorted(missing_ids)}"
    else:
        id_score = 40
        reason = "All expected ids present"
    total_score += add_detail("Correct set of document ids (exact match)", id_score, max_id_score, not missing_ids, reason)

    # 6. No extra ids
    extra_score = 0
    max_extra_score = 10
    if extra_ids:
        # -2 per extra id, min 0
        extra_score = max(0, max_extra_score - 2 * len(extra_ids))
        reason = f"Extra ids found: {sorted(extra_ids)}"
    else:
        extra_score = max_extra_score
        reason = "No extra ids"
    total_score += add_detail("No extra unwanted ids", extra_score, max_extra_score, not bool(extra_ids), reason)

    # 7. Clue content (first 80 chars of summary) per expected document
    clue_content_score = 0
    max_clue_score = 20  # 4 per match, 5 matches
    for c in clues:
        cid = c["id"]
        if cid in expected:
            # compute expected clue: first 80 characters of the summary
            exp_summary = expected[cid]["summary"]
            exp_clue = exp_summary[:80]
            if c.get("clue", "") == exp_clue:
                clue_content_score += 4
                add_detail(f"Clue for {cid} matches first 80 chars", 4, 4, True, "Exact match")
            else:
                # partial? We'll give 0 for that entry
                add_detail(f"Clue for {cid} matches first 80 chars", 0, 4, False,
                           f"Expected '{exp_clue[:40]}...' got '{c.get('clue','')[:40]}...'")
    total_score += clue_content_score

    # Write final score
    _write_score(total_score, details, wdir)


def _write_score(total_score, details, wdir):
    score_data = {
        "total_score": min(100, total_score),  # cap at 100
        "details": details
    }
    score_path = wdir / "workplace_score.json"
    with open(score_path, "w") as f:
        json.dump(score_data, f, indent=2)
    print(f"Score written: {score_data['total_score']}/100")


if __name__ == "__main__":
    main()
