#!/usr/bin/env python3

import argparse


def main():
    parser = argparse.ArgumentParser(description="Finish the task and output the final answer.")
    parser.add_argument("--answer", required=True, type=str, help="Final answer")
    args = parser.parse_args()

    print(args.answer)


if __name__ == "__main__":
    main()
