"""
System Logging Environment API

A system logging environment that collects, stores, and manages event records
generated by software applications, operating systems, or network devices.
"""

from copy import deepcopy
from typing import Dict, List, Optional, Any
from datetime import datetime, timedelta

# Default initial state for the system logging environment
DEFAULT_STATE = {
    # Log entries storage - list of log entry dictionaries
    "log_entries": [
        {
            "event_id": "EVT-001",
            "timestamp": "2024-01-15T10:30:00Z",
            "severity": "INFO",
            "message": "Application started successfully",
            "source_component": "auth-service",
            "host_machine": "server-01"
        },
        {
            "event_id": "EVT-002",
            "timestamp": "2024-01-15T10:31:15Z",
            "severity": "WARNING",
            "message": "High memory usage detected",
            "source_component": "monitoring-agent",
            "host_machine": "server-02"
        },
        {
            "event_id": "EVT-003",
            "timestamp": "2024-01-15T10:32:45Z",
            "severity": "ERROR",
            "message": "Database connection failed",
            "source_component": "data-service",
            "host_machine": "server-01"
        },
        {
            "event_id": "EVT-004",
            "timestamp": "2024-01-15T10:33:00Z",
            "severity": "DEBUG",
            "message": "Cache invalidation triggered",
            "source_component": "cache-manager",
            "host_machine": "server-03"
        },
        {
            "event_id": "EVT-005",
            "timestamp": "2024-01-15T10:35:30Z",
            "severity": "INFO",
            "message": "User login successful",
            "source_component": "auth-service",
            "host_machine": "server-01"
        }
    ],
    
    # Log repository configuration
    "repository": {
        "storage_capacity": 1000000,  # Maximum number of log entries
        "retention_policy": 2592000,  # 30 days in seconds
        "indexed_fields": ["event_id", "timestamp", "severity", "source_component", "host_machine"]
    },
    
    # Current user context for audit purposes
    "current_user": "system_admin",
    
    # Session information
    "session": {
        "session_id": "sess-abc123",
        "started_at": "2024-01-15T10:00:00Z"
    }
}


class SystemLoggingEnvironment:
    """
    System Logging Environment API for managing log entries and repository operations.
    
    This environment provides operations to insert, query, and manage log entries
    in a centralized repository. It enforces write-once semantics, retention policies,
    and supports querying on indexed fields only.
    """
    
    def __init__(self):
        """
        Initialize the System Logging Environment.
        
        Declares all state attributes with type hints and sets up the API description.
        
        Args:
            None
        
        Returns:
            None
        """
        self.log_entries: List[Dict[str, Any]] = []
        self.repository: Dict[str, Any] = {}
        self.current_user: str = ""
        self.session: Dict[str, str] = {}
        
        self._api_description: str = (
            "A system logging environment API for collecting, storing, and managing "
            "event records with support for querying, filtering, and audit operations."
        )
    
    def _timestamp(self) -> str:
        """
        Generate a unified ISO format timestamp string.
        
        Args:
            None
        
        Returns:
            str: Current timestamp in ISO 8601 format (e.g., '2024-01-15T10:30:00Z').
        """
        return datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    
    def _load_scenario(self, scenario: dict, long_context: bool = False) -> None:
        """
        Load initial state from a scenario dictionary.
        
        Initializes the environment state from the provided scenario. If a key
        is missing from the scenario, falls back to DEFAULT_STATE values.
        
        Args:
            scenario: Dictionary containing initial state values.
            long_context: Flag for extended context scenarios (unused in base implementation).
        
        Returns:
            None
        """
        if not scenario:
            scenario = {}
        for key in DEFAULT_STATE:
            if key in scenario:
                setattr(self, key, deepcopy(scenario[key]))
            else:
                setattr(self, key, deepcopy(DEFAULT_STATE[key]))
    
    def get_env_state(self) -> dict:
        """
        Retrieve the current environment state.
        
        Returns a dictionary containing all internal state variables of the
        logging environment, including log entries, repository configuration,
        and session information.
        
        Args:
            None
        
        Returns:
            dict: A dictionary containing:
                - log_entries (List[Dict]): All stored log entries.
                - repository (Dict): Repository configuration including capacity,
                  retention policy, and indexed fields.
                - current_user (str): The current user context.
                - session (Dict): Current session information.
        """
        return {
            "log_entries": deepcopy(self.log_entries),
            "repository": deepcopy(self.repository),
            "current_user": self.current_user,
            "session": deepcopy(self.session)
        }
    
    # ==================== Query Operations ====================
    
    def get_log_entry_by_id(self, event_id: str) -> Dict[str, Any]:
        """
        Retrieve a single log entry using its unique event_id.
        
        Args:
            event_id: The unique identifier of the log entry to retrieve.
        
        Returns:
            dict: The log entry if found, or an error dictionary if not found.
                  Success: {"log_entry": {...log entry data...}}
                  Error: {"error": "Log entry not found"}
        """
        if not event_id:
            return {"error": "event_id parameter is required"}
        
        for entry in self.log_entries:
            if entry.get("event_id") == event_id:
                return {"log_entry": deepcopy(entry)}
        
        return {"error": f"Log entry with event_id '{event_id}' not found"}
    
    def list_log_entries_by_ids(self, event_ids: List[str]) -> Dict[str, Any]:
        """
        Retrieve multiple log entries for a given list of event_ids.
        
        Args:
            event_ids: List of event identifiers to retrieve.
        
        Returns:
            dict: Dictionary containing found entries and any missing IDs.
                  {"log_entries": [...], "missing_ids": [...], "total_found": int}
        """
        if not event_ids:
            return {"error": "event_ids parameter is required and cannot be empty"}
        
        if not isinstance(event_ids, list):
            return {"error": "event_ids must be a list"}
        
        found_entries = []
        missing_ids = []
        
        for event_id in event_ids:
            entry_found = False
            for entry in self.log_entries:
                if entry.get("event_id") == event_id:
                    found_entries.append(deepcopy(entry))
                    entry_found = True
                    break
            if not entry_found:
                missing_ids.append(event_id)
        
        return {
            "log_entries": found_entries,
            "missing_ids": missing_ids,
            "total_found": len(found_entries)
        }
    
    def query_logs_by_severity(self, severity: str) -> Dict[str, Any]:
        """
        Retrieve all log entries matching a specific severity level.
        
        Args:
            severity: The severity level to filter by (e.g., 'INFO', 'WARNING', 'ERROR', 'DEBUG').
        
        Returns:
            dict: Dictionary containing matching log entries.
                  {"log_entries": [...], "count": int, "severity_filter": str}
        """
        if not severity:
            return {"error": "severity parameter is required"}
        
        # Check if severity is an indexed field
        if "severity" not in self.repository.get("indexed_fields", []):
            return {"error": "severity field is not indexed and cannot be queried"}
        
        matching_entries = [
            deepcopy(entry) for entry in self.log_entries
            if entry.get("severity", "").upper() == severity.upper()
        ]
        
        return {
            "log_entries": matching_entries,
            "count": len(matching_entries),
            "severity_filter": severity.upper()
        }
    
    def query_logs_by_time_range(
        self, 
        start_timestamp: str, 
        end_timestamp: str
    ) -> Dict[str, Any]:
        """
        Retrieve log entries within a specified timestamp range.
        
        Args:
            start_timestamp: ISO format start time (inclusive).
            end_timestamp: ISO format end time (inclusive).
        
        Returns:
            dict: Dictionary containing log entries within the time range.
                  {"log_entries": [...], "count": int, "time_range": {...}}
        """
        if not start_timestamp or not end_timestamp:
            return {"error": "Both start_timestamp and end_timestamp are required"}
        
        # Check if timestamp is an indexed field
        if "timestamp" not in self.repository.get("indexed_fields", []):
            return {"error": "timestamp field is not indexed and cannot be queried"}
        
        try:
            start_dt = datetime.fromisoformat(start_timestamp.replace("Z", "+00:00"))
            end_dt = datetime.fromisoformat(end_timestamp.replace("Z", "+00:00"))
        except ValueError as e:
            return {"error": f"Invalid timestamp format: {str(e)}"}
        
        if start_dt > end_dt:
            return {"error": "start_timestamp must be before or equal to end_timestamp"}
        
        matching_entries = []
        for entry in self.log_entries:
            try:
                entry_ts = entry.get("timestamp", "")
                entry_dt = datetime.fromisoformat(entry_ts.replace("Z", "+00:00"))
                if start_dt <= entry_dt <= end_dt:
                    matching_entries.append(deepcopy(entry))
            except (ValueError, TypeError):
                continue
        
        return {
            "log_entries": matching_entries,
            "count": len(matching_entries),
            "time_range": {
                "start": start_timestamp,
                "end": end_timestamp
            }
        }
    
    def query_logs_by_source_component(self, source_component: str) -> Dict[str, Any]:
        """
        Retrieve log entries generated by a specific software component or service.
        
        Args:
            source_component: The name of the source component to filter by.
        
        Returns:
            dict: Dictionary containing matching log entries.
                  {"log_entries": [...], "count": int, "source_component_filter": str}
        """
        if not source_component:
            return {"error": "source_component parameter is required"}
        
        # Check if source_component is an indexed field
        if "source_component" not in self.repository.get("indexed_fields", []):
            return {"error": "source_component field is not indexed and cannot be queried"}
        
        matching_entries = [
            deepcopy(entry) for entry in self.log_entries
            if entry.get("source_component") == source_component
        ]
        
        return {
            "log_entries": matching_entries,
            "count": len(matching_entries),
            "source_component_filter": source_component
        }
    
    def query_logs_by_host_machine(self, host_machine: str) -> Dict[str, Any]:
        """
        Retrieve log entries originating from a specific machine.
        
        Args:
            host_machine: The hostname or identifier of the machine to filter by.
        
        Returns:
            dict: Dictionary containing matching log entries.
                  {"log_entries": [...], "count": int, "host_machine_filter": str}
        """
        if not host_machine:
            return {"error": "host_machine parameter is required"}
        
        # Check if host_machine is an indexed field
        if "host_machine" not in self.repository.get("indexed_fields", []):
            return {"error": "host_machine field is not indexed and cannot be queried"}
        
        matching_entries = [
            deepcopy(entry) for entry in self.log_entries
            if entry.get("host_machine") == host_machine
        ]
        
        return {
            "log_entries": matching_entries,
            "count": len(matching_entries),
            "host_machine_filter": host_machine
        }
    
    def list_all_indexed_fields(self) -> Dict[str, Any]:
        """
        Return the list of fields that support querying.
        
        Args:
            None
        
        Returns:
            dict: Dictionary containing the list of indexed fields.
                  {"indexed_fields": [...], "count": int}
        """
        indexed_fields = self.repository.get("indexed_fields", [])
        
        return {
            "indexed_fields": deepcopy(indexed_fields),
            "count": len(indexed_fields)
        }
    
    def get_repository_status(self) -> Dict[str, Any]:
        """
        Retrieve current log repository statistics.
        
        Args:
            None
        
        Returns:
            dict: Dictionary containing repository statistics including
                  number of entries, storage usage, and configuration.
        """
        total_entries = len(self.log_entries)
        storage_capacity = self.repository.get("storage_capacity", 0)
        
        # Calculate storage usage percentage
        usage_percentage = (total_entries / storage_capacity * 100) if storage_capacity > 0 else 0
        
        # Count entries by severity
        severity_counts = {}
        for entry in self.log_entries:
            severity = entry.get("severity", "UNKNOWN")
            severity_counts[severity] = severity_counts.get(severity, 0) + 1
        
        return {
            "total_entries": total_entries,
            "storage_capacity": storage_capacity,
            "storage_usage_percentage": round(usage_percentage, 2),
            "retention_policy_seconds": self.repository.get("retention_policy", 0),
            "indexed_fields": deepcopy(self.repository.get("indexed_fields", [])),
            "severity_distribution": severity_counts
        }
    
    # ==================== State Change Operations ====================
    
    def insert_log_entry(
        self,
        event_id: str,
        severity: str,
        message: str,
        source_component: str,
        host_machine: str,
        timestamp: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Add a new log entry to the repository.
        
        Fails if event_id already exists (enforces uniqueness constraint).
        
        Args:
            event_id: Unique identifier for the log entry.
            severity: Severity level (e.g., 'INFO', 'WARNING', 'ERROR', 'DEBUG').
            message: Descriptive message for the log entry.
            source_component: The software component generating the log.
            host_machine: The machine where the event originated.
            timestamp: Optional ISO format timestamp; defaults to current time.
        
        Returns:
            dict: Success status or error message.
                  Success: {"success": True, "log_entry": {...}, "message": str}
                  Error: {"error": "..."}
        """
        # Validate required fields
        if not event_id:
            return {"error": "event_id is required"}
        if not severity:
            return {"error": "severity is required"}
        if not message:
            return {"error": "message is required"}
        if not source_component:
            return {"error": "source_component is required"}
        if not host_machine:
            return {"error": "host_machine is required"}
        
        # Constraint: Each LogEntry must have a unique event_id
        for entry in self.log_entries:
            if entry.get("event_id") == event_id:
                return {"error": f"Log entry with event_id '{event_id}' already exists"}
        
        # Check storage capacity
        if len(self.log_entries) >= self.repository.get("storage_capacity", float("inf")):
            return {"error": "Repository storage capacity exceeded"}
        
        # Create new log entry
        new_entry = {
            "event_id": event_id,
            "timestamp": timestamp if timestamp else self._timestamp(),
            "severity": severity.upper(),
            "message": message,
            "source_component": source_component,
            "host_machine": host_machine
        }
        
        self.log_entries.append(new_entry)
        
        return {
            "success": True,
            "log_entry": deepcopy(new_entry),
            "message": f"Log entry '{event_id}' inserted successfully"
        }
    
    def purge_expired_logs(self, reference_timestamp: Optional[str] = None) -> Dict[str, Any]:
        """
        Remove all log entries older than the retention policy allows.
        
        Args:
            reference_timestamp: Optional reference time for calculating expiry.
                                 Defaults to current time if not provided.
        
        Returns:
            dict: Summary of purge operation including count of removed entries.
                  {"success": True, "purged_count": int, "remaining_count": int, "cutoff_timestamp": str}
        """
        retention_seconds = self.repository.get("retention_policy", 0)
        
        if retention_seconds <= 0:
            return {"error": "Invalid retention policy configured"}
        
        # Determine reference time
        if reference_timestamp:
            try:
                ref_dt = datetime.fromisoformat(reference_timestamp.replace("Z", "+00:00"))
            except ValueError:
                return {"error": "Invalid reference_timestamp format"}
        else:
            ref_dt = datetime.utcnow()
        
        # Calculate cutoff time
        cutoff_dt = ref_dt - timedelta(seconds=retention_seconds)
        
        original_count = len(self.log_entries)
        retained_entries = []
        purged_count = 0
        
        for entry in self.log_entries:
            try:
                entry_ts = entry.get("timestamp", "")
                entry_dt = datetime.fromisoformat(entry_ts.replace("Z", "+00:00"))
                if entry_dt >= cutoff_dt:
                    retained_entries.append(entry)
                else:
                    purged_count += 1
            except (ValueError, TypeError):
                # Keep entries with invalid timestamps
                retained_entries.append(entry)
        
        self.log_entries = retained_entries
        
        return {
            "success": True,
            "purged_count": purged_count,
            "remaining_count": len(self.log_entries),
            "cutoff_timestamp": cutoff_dt.strftime("%Y-%m-%dT%H:%M:%SZ")
        }
    
    def update_retention_policy(self, retention_seconds: int) -> Dict[str, Any]:
        """
        Modify the retention period (in seconds) for stored log entries.
        
        Args:
            retention_seconds: New retention period in seconds (must be positive).
        
        Returns:
            dict: Success status with old and new retention values.
                  {"success": True, "old_retention": int, "new_retention": int, "message": str}
        """
        if not isinstance(retention_seconds, int):
            return {"error": "retention_seconds must be an integer"}
        
        if retention_seconds <= 0:
            return {"error": "retention_seconds must be a positive integer"}
        
        old_retention = self.repository.get("retention_policy", 0)
        self.repository["retention_policy"] = retention_seconds
        
        return {
            "success": True,
            "old_retention": old_retention,
            "new_retention": retention_seconds,
            "message": f"Retention policy updated from {old_retention}s to {retention_seconds}s"
        }
    
    def update_indexed_fields(self, indexed_fields: List[str]) -> Dict[str, Any]:
        """
        Update the set of fields that support query operations.
        
        Args:
            indexed_fields: List of field names to be indexed.
        
        Returns:
            dict: Success status with old and new indexed fields.
                  {"success": True, "old_fields": [...], "new_fields": [...], "message": str}
        """
        if not indexed_fields:
            return {"error": "indexed_fields parameter is required and cannot be empty"}
        
        if not isinstance(indexed_fields, list):
            return {"error": "indexed_fields must be a list"}
        
        # Validate that all provided fields are valid log entry attributes
        valid_fields = {"event_id", "timestamp", "severity", "message", "source_component", "host_machine"}
        invalid_fields = [f for f in indexed_fields if f not in valid_fields]
        
        if invalid_fields:
            return {
                "error": f"Invalid field names: {invalid_fields}. Valid fields are: {list(valid_fields)}"
            }
        
        old_fields = deepcopy(self.repository.get("indexed_fields", []))
        self.repository["indexed_fields"] = list(set(indexed_fields))  # Remove duplicates
        
        return {
            "success": True,
            "old_fields": old_fields,
            "new_fields": deepcopy(self.repository["indexed_fields"]),
            "message": "Indexed fields updated successfully"
        }
    
    def clear_all_logs(self, confirm: bool = False) -> Dict[str, Any]:
        """
        Remove all log entries (admin-level operation).
        
        This is a destructive operation useful for testing or environment reset.
        Requires explicit confirmation.
        
        Args:
            confirm: Must be True to execute the clear operation.
        
        Returns:
            dict: Success status with count of cleared entries.
                  {"success": True, "cleared_count": int, "message": str}
        """
        if not confirm:
            return {
                "error": "This operation requires explicit confirmation. Set confirm=True to proceed."
            }
        
        cleared_count = len(self.log_entries)
        self.log_entries = []
        
        return {
            "success": True,
            "cleared_count": cleared_count,
            "message": f"All {cleared_count} log entries have been cleared"
        }


# Test cases for the System Logging Environment
__TEST_CASES__ = [
    {
        "name": "Query and retrieve log entries workflow",
        "steps": [
            {"tool_call": "get_log_entry_by_id(event_id='EVT-001')", "expect_success": True},
            {"tool_call": "list_log_entries_by_ids(event_ids=['EVT-001', 'EVT-002', 'EVT-003'])", "expect_success": True},
            {"tool_call": "query_logs_by_severity(severity='ERROR')", "expect_success": True},
            {"tool_call": "get_repository_status()", "expect_success": True}
        ]
    },
    {
        "name": "Insert new log entry and verify",
        "steps": [
            {"tool_call": "insert_log_entry(event_id='EVT-100', severity='INFO', message='New test event', source_component='test-service', host_machine='server-01')", "expect_success": True},
            {"tool_call": "get_log_entry_by_id(event_id='EVT-100')", "expect_success": True},
            {"tool_call": "query_logs_by_source_component(source_component='test-service')", "expect_success": True}
        ]
    },
    {
        "name": "Error handling - duplicate event_id",
        "steps": [
            {"tool_call": "get_log_entry_by_id(event_id='EVT-001')", "expect_success": True},
            {"tool_call": "insert_log_entry(event_id='EVT-001', severity='WARNING', message='Duplicate test', source_component='test-service', host_machine='server-01')", "expect_success": False}
        ]
    },
    {
        "name": "Update repository configuration",
        "steps": [
            {"tool_call": "list_all_indexed_fields()", "expect_success": True},
            {"tool_call": "update_retention_policy(retention_seconds=604800)", "expect_success": True},
            {"tool_call": "update_indexed_fields(indexed_fields=['event_id', 'timestamp', 'severity'])", "expect_success": True},
            {"tool_call": "get_repository_status()", "expect_success": True}
        ]
    },
    {
        "name": "Error handling - query non-existent entry and invalid parameters",
        "steps": [
            {"tool_call": "get_log_entry_by_id(event_id='NON-EXISTENT-ID')", "expect_success": False},
            {"tool_call": "update_retention_policy(retention_seconds=-100)", "expect_success": False},
            {"tool_call": "clear_all_logs(confirm=False)", "expect_success": False}
        ]
    }
]